# Generated by Django 3.2 on 2022-10-20 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelInputs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nedbank_cc', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('money_app', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('greenbacks_flag', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=60)),
                ('profile_segmentation', models.CharField(choices=[('PROFILE_SEGMENT_LEVEL_2_Emerging Middle Market Adult', 'PROFILE_SEGMENT_LEVEL_2_Emerging Middle Market Adult'), ('PROFILE_SEGMENT_LEVEL_2_Emerging Middle Market Senior', 'PROFILE_SEGMENT_LEVEL_2_Emerging Middle Market Senior'), ('PROFILE_SEGMENT_LEVEL_2_Established Middle Market Adult', 'PROFILE_SEGMENT_LEVEL_2_Established Middle Market Adult'), ('PROFILE_SEGMENT_LEVEL_2_Established Middle Market Senior', 'PROFILE_SEGMENT_LEVEL_2_Established Middle Market Senior'), ('PROFILE_SEGMENT_LEVEL_2_Established Professional', 'PROFILE_SEGMENT_LEVEL_2_Established Professional'), ('PROFILE_SEGMENT_LEVEL_2_Established Professional Senior', 'PROFILE_SEGMENT_LEVEL_2_Established Professional Senior'), ('PROFILE_SEGMENT_LEVEL_2_Lower ELB ', 'PROFILE_SEGMENT_LEVEL_2_Lower ELB '), ('PROFILE_SEGMENT_LEVEL_2_Other', 'PROFILE_SEGMENT_LEVEL_2_Other'), ('PROFILE_SEGMENT_LEVEL_2_Upper ELB', 'PROFILE_SEGMENT_LEVEL_2_Upper ELB'), ('PROFILE_SEGMENT_LEVEL_2_Young Professional', 'PROFILE_SEGMENT_LEVEL_2_Young Professional'), ('PROFILE_SEGMENT_LEVEL_2_Youth Kids and Teens', 'PROFILE_SEGMENT_LEVEL_2_Youth Kids and Teens'), ('PROFILE_SEGMENT_LEVEL_2_Youth Upwardly Mobile', 'PROFILE_SEGMENT_LEVEL_2_Youth Upwardly Mobile'), ('PROFILE_SEGMENT_LEVEL_2_Youth Young Adults', 'PROFILE_SEGMENT_LEVEL_2_Youth Young Adults')], max_length=60)),
                ('Race', models.CharField(choices=[('RACE_Asian', 'RACE_Asian'), ('RACE_Black', 'RACE_Black'), ('RACE_Coloured', 'RACE_Coloured'), ('RACE_Unknown', 'RACE_Unknown'), ('RACE_White', 'RACE_White')], max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
